core/urls.py
from rest_framework import routers

from core import views


app_name = "core"


router = routers.SimpleRouter()
router.register(r"discount-cards", views.DiscountCardViewSet,
                basename="discount-card")

urlpatterns = router.urls

discount_cards/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import DiscountCardListView, DiscountCardView, DiscountCardUpdateStatusView


app_name = "discount_cards"


urlpatterns = [
    path("list/", DiscountCardListView.as_view(), name="card-list"),
    path("<int:pk>/", DiscountCardView.as_view(),
         name="card_detail"),
    path("edit/<int:pk>/", DiscountCardUpdateStatusView.as_view(),
         name="edit_card"),
    # path("delete/<int:pk>/", DiscountCardDeleteView.as_view(),
    #      name="delete_card"),
    path("", RedirectView.as_view(url="list/")),
]

django_discount_cards/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("discount-cards/", include("discount_cards.urls")),
    path("api/v1/", include("core.urls"), name="api"),
    path("", RedirectView.as_view(url="discount-cards/")),
]

core/models.py
from django.db import models

# Create your models here.

discount_cards/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
User = get_user_model()


class DiscountCard(models.Model):
    STATUS_CHOICES = [
        (True, _("discount_card.active")),
        (False, _("discount_card.not_active")),
    ]
    seria = models.CharField(_("discount_card.seria"), max_length=2)
    number = models.PositiveIntegerField(_("discount_card.number"))
    release_date = models.DateTimeField(_("discount_card.release_date"))
    end_date = models.DateTimeField(_("discount_card.end_date"))
    last_use = models.DateTimeField(_("discount_card.last_use"))
    sum = models.DecimalField(_("discount_card.sum"), max_digits=19,
                              decimal_places=4)
    status = models.BooleanField(_("discount_card.status"),
                                 choices=STATUS_CHOICES)
    user = models.ForeignKey(User, on_delete=models.PROTECT,
                             verbose_name=_("discount_card.user"))

    def __str__(self):
        return f"{self.seria} {self.number}"

    class Meta:
        verbose_name = _("discount_card")
        verbose_name_plural = _("discount_cards")


class Purchase(models.Model):
    discount_card = models.ForeignKey(DiscountCard, on_delete=models.CASCADE,
                                      verbose_name=_("purchase.purchase"),
                                      related_name="purchases")
    date = models.DateTimeField(_("purchase.date"), auto_now=True)
    purchase_amount = models.DecimalField(_("purchase.purchase_amount"),
                                          max_digits=19, decimal_places=4)

    def __str__(self):
        return f"{self.discount_card} - {self.date} - {self.purchase_amount}"

    class Meta:
        verbose_name = _("purchase")
        verbose_name_plural = _("purchases")

discount_cards/forms.py
from django.forms import ModelForm

from .models import DiscountCard, Purchase


class DiscountCardForm(ModelForm):
    class Meta:
        model = DiscountCard
        fields = "__all__"


class ReadOnlyDiscountCardForm(ModelForm):
    class Meta:
        model = DiscountCard
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["readonly"] = True


class PurchaseForm(ModelForm):
    class Meta:
        model = Purchase
        fields = "__all__"

core/views.py
from django.shortcuts import get_object_or_404

from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters
from rest_framework.viewsets import ModelViewSet
from rest_framework.response import Response

from discount_cards.models import DiscountCard
from .serializers import DiscountCardSerializer, DiscountCardRetrieveSerializer


class DiscountCardViewSet(ModelViewSet):
    filter_backends = (filters.SearchFilter, filters.OrderingFilter,
                       DjangoFilterBackend)
    search_fields = ("seria", "number", "status", "end_date")
    ordering_fields = ("-release_date",)
    filterset_fields = "__all__"
    serializer_class = DiscountCardSerializer

    def get_queryset(self):
        return DiscountCard.objects.select_related("user")

    def retrieve(self, request, pk, *args, **kwargs):
        queryset = DiscountCard.objects.all()
        discount_card = get_object_or_404(queryset, pk=pk)
        serializer = DiscountCardRetrieveSerializer(discount_card)
        return Response(serializer.data)

discount_cards/views.py
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from .models import DiscountCard, Purchase
from .forms import ReadOnlyDiscountCardForm


class DiscountCardView(DetailView):
    model = DiscountCard
    template_name = "discount_cards/single.html"
    context_object_name = "discount_card"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        card = kwargs["object"]
        purchases = Purchase.objects.filter(discount_card_id=card.id)
        card_form = ReadOnlyDiscountCardForm(instance=card)
        context["card"] = card
        context["purchases"] = purchases
        context["card_form"] = card_form
        return context


class DiscountCardListView(ListView):
    model = DiscountCard
    template_name = "discount_cards/discount_cards_list.html"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cards = self.get_queryset()
        page = self.request.GET.get("page")
        paginator = Paginator(cards, self.paginate_by)
        try:
            cards = paginator.page(page)
        except PageNotAnInteger:
            cards = paginator.page(1)
        except EmptyPage:
            cards = paginator.page(paginator.num_pages)
        context["cards"] = cards
        return context


class DiscountCardUpdateStatusView(UpdateView):
    model = DiscountCard
    fields = ["status"]
    template_name = "discount_cards/change_status.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_success_url(self):
        return reverse("discount_cards:edit_card", kwargs={"pk": self.object.pk})

    def get_absolute_url(self):
        return reverse("discount_cards:edit_card", kwargs={"pk": self.object.pk})

discount_cards/templates/discount_cards/base.html
{% spaceless %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% load static %}
{% load cache %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block meta_tags %}{% endblock %}
  <title>{% block title %}{% trans "discount_card" %}{% endblock %}</title>
  {% block css %}
  <link rel="stylesheet" href="{% static 'discount_cards/bootstrap.min.css' %}">
  {% endblock %}
  {% block custom_css %}
  {% endblock %}
</head>
<body>
  {% block header %}{% include "discount_cards/header.html" %}{% endblock header %}
  {% block content %}{% endblock content %}
  {% block footer %}{% include "discount_cards/footer.html" %}{% endblock footer %}
  <script src="{% static 'discount_cards/jquery-3.4.1.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'discount_cards/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'discount_cards/script.js' %}" type="text/javascript"></script>
</body>
</html>
{% endspaceless %}

discount_cards/templates/discount_cards/change_status.html
{% extends "discount_cards/base.html" %}
{% spaceless %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% load cache %}
{% load crispy_forms_tags %}

{% block title %}{% trans "change_status" %}{% endblock title %}

{% block content %}
<main>
  <div class="container">
    <div class="row pt-3 pb-3">
      <div class="col-md-12 d-sm-flex text-center justify-content-center">
        <h1 class="h2">{% trans "change_status" %}</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md">
        <form class="" method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-dark text-white">{% trans "submit" %}</button>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}
{% endspaceless %}

discount_cards/templates/discount_cards/discount_cards_list.html
{% extends "discount_cards/base.html" %}
{% spaceless %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% load cache %}

{% block title %}{% trans "discount_card_list" %}{% endblock title %}

{% block content %}
<main>
  <div class="container">
    <div class="row pt-3 pb-3">
      <div class="col-md-12 d-sm-flex text-center justify-content-center">
        <h1 class="h2">{% trans "discount_card_list" %}</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md">
        <table class="table">
          <tr>
            <thead class="thead-light">
              <tr>
                <th scope="col">{% trans "discount_card.seria" %}</th>
                <th scope="col">{% trans "discount_card.number" %}</th>
                <th scope="col">{% trans "discount_card.end_date" %}</th>
                <th scope="col">{% trans "discount_card.status" %}</th>
                <th scope="col">{% trans "discount_card.button_details" %}</th>
                <th scope="col">{% trans "discount_card.button_edit" %}</th>
                <th scope="col">{% trans "discount_card.button_delete" %}</th>
              </tr>
            </thead>
            <tbody>
              {% for card in cards %}
              <tr data-row="">
                <td>{{ card.seria }}</td>
                <td>{{ card.number }}</td>
                <td>{{ card.end_date }}</td>
                <td>
                {% if card.status %}
                  {% trans "discount_card.active" %}
                {% else %}
                  {% trans "discount_card.not_active" %}
                {% endif %}
                </td>
                <td><a class="btn btn-dark text-white" href="{% url 'discount_cards:card_detail' card.id %}">{% trans "discount_cards.card_detail" %}</a></td>
                <td><a class="btn btn-dark text-white" href="{% url 'discount_cards:edit_card' card.id %}">{% trans "discount_cards.edit_card" %}</a></td>
                <td><button class="btn btn-danger text-white delete-btn" data-id="{{ card.id }}" data-name="Серия {{ card.seria }}, Номер {{ card.number }}" data-delete-url="{% url 'core:discount-card-detail' card.id %}">{% trans 'discount_cards.delete_card' %}</button></td>
              </tr>
              {% endfor %}
            </tbody>
        </table>
        {% if is_paginated %}
          {% include "_pagination.html" %}
        {% endif %}
      </div>
    </div>
  </div>
</main>
{% endblock %}
{% endspaceless %}

discount_cards/templates/discount_cards/footer.html
{% spaceless %}
{% load static %}
<footer class="page-footer">
  <hr>
  <div class="container">
    <p>&copy; Viacheslav Loievskyi</p>
  </div>
</footer>
{% endspaceless %}

discount_cards/templates/discount_cards/header.html
{% spaceless %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% load static %}
{% load cache %}
<header class="page-header sticky-top">
  <nav class="navbar navbar-expand-md navbar-fixed-top navbar-dark bg-dark" role="navigation">
    <div class="container">
      <a class="navbar-brand" href="#"">{% trans "discount_cards" %}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'discount_cards:card-list' %}">{% trans "discount_cards.card_list" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'core:discount-card-list' %}">{% trans "API" %}</a>
          </li>
        </ul>
        {% comment %}
        <form class="form-inline my-2 my-lg-0 flex-nowrap">
          <input class="form-control mr-2 custom-search-input" type="search" aria-label="search">
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">{% trans "search" %}</button>
        </form>
        {% endcomment %}
      </div>
    </div>
  </nav>
</header>
{% endspaceless %}

discount_cards/templates/discount_cards/single.html
{% extends "discount_cards/base.html" %}
{% spaceless %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% load cache %}
{% load crispy_forms_tags %}

{% block title %}{% trans "discount_card" %}{% endblock title %}

{% block content %}
<main>
  <div class="container">
    <div class="row pt-3 pb-3">
      <div class="col-md-12 d-sm-flex text-center justify-content-center">
        <h1 class="h2">{% trans "discount_card" %}</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md">
        <form class="" action="index.html" method="post">
          {% csrf_token %}
          {{ card_form|crispy }}
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col-md">
        <table class="table">
          <tr>
            <thead class="thead-light">
              <tr>
                <th scope="col">{% trans "purchase.date" %}</th>
                <th scope="col">{% trans "purchase.purchase_amount" %}</th>
              </tr>
            </thead>
            <tbody>
              {% for purchase in purchases %}
              <tr>
                <td>{{ purchase.date }}</td>
                <td>{{ purchase.purchase_amount }}</td>
              </tr>
              {% endfor %}
            </tbody>
        </table>
        {% if is_paginated %}
          {% include "_pagination.html" %}
        {% endif %}
      </div>
    </div>
  </div>
</main>
{% endblock %}
{% endspaceless %}